ViewModels/ShoppingCartViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Timups.Models;

namespace Timups.ViewModels
{
    public class ShoppingCartViewModel
    {
        public ShoppingCart ShoppingCart { get; set; }
        public decimal ShoppingCartTotal { get; set; }
    }
}

Controllers/OrderController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Timups.Models;
using Timups.Data.Interfaces;
using Microsoft.AspNetCore.Authorization;

namespace Timups.Controllers
{
    public class OrderController : Controller
    {
        private readonly IOrderRepository _orderRepository;
        private readonly ShoppingCart _shoppingCart;


        public OrderController(IOrderRepository orderRepository, ShoppingCart shoppingCart)
        {
            _orderRepository = orderRepository;
            _shoppingCart = shoppingCart;
        }
        [Authorize]
        public IActionResult CheckOut()
        {
            return View();
        }
        
        [HttpPost]
        [Authorize]
        public IActionResult Checkout(Order order)
        {
            var items = _shoppingCart.GetShoppingCartItems();
            _shoppingCart.ShoppingCartItems = items;
            if (_shoppingCart.ShoppingCartItems.Count == 0)
            {
                ModelState.AddModelError("", "Your card is empty, add some watches first");
            }

            if (ModelState.IsValid)
            {
                _orderRepository.CreateOrder(order);
                _shoppingCart.ClearCart();
                return RedirectToAction("CheckoutComplete");
            }

            return View(order);
        }

        public IActionResult CheckoutComplete()
        {
            ViewBag.CheckoutCompleteMessage = "Thanks for your order! ";
            return View();
        }
    }
}

Controllers/ShoppingCartController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Timups.Data.Interfaces;
using Timups.Models;
using Timups.ViewModels;

namespace Timups.Controllers
{
    public class ShoppingCartController : Controller
    {
        private readonly IWatchRepository _watchRepository;
        private readonly ShoppingCart _shoppingCart;
        public ShoppingCartController(IWatchRepository watchRepository, ShoppingCart shoppingCart)
        {
            _watchRepository = watchRepository;
            _shoppingCart = shoppingCart;
        }
        public ViewResult Index()
        {
            var items = _shoppingCart.GetShoppingCartItems();
            _shoppingCart.ShoppingCartItems = items;

            var shoppingCartViewModel = new ShoppingCartViewModel
            {
                ShoppingCart = _shoppingCart,
                ShoppingCartTotal = _shoppingCart.GetShoppingCartTotal()
            };

            return View(shoppingCartViewModel);
        }

        public RedirectToActionResult AddToShoppingCart (int watchId)
        {
            var selectedWatch = _watchRepository.Watches.FirstOrDefault(p => p.WatchId == watchId);
            if (selectedWatch != null)
            {
                _shoppingCart.AddToCart(selectedWatch, 1);
            }
            return RedirectToAction("Index");
        }

        public RedirectToActionResult RemoveFromShoppingCart(int watchId)
        {
            var selectedWatch = _watchRepository.Watches.FirstOrDefault(p => p.WatchId == watchId);
            if (selectedWatch != null)
            {
                _shoppingCart.RemoveFromCart(selectedWatch);
            }
            return RedirectToAction("Index");
        }
    }
}

Views/ShoppingCart/Index.cshtml
@{
    ViewData["Title"] = "Shopping Cart Page";
}

@model ShoppingCartViewModel
@await Html.PartialAsync("Header")
<!-- shopping cart section -->
<section class="contact_section layout_padding">
    <div class="container">
        <div class="row checkoutForm">
            <h2>Your shopping cart</h2>

            <table class="table table-bordered table-striped">
                <thead>
                    <tr>
                        <th>Selected amount</th>
                        <th>Watch</th>
                        <th class="text-right">Price</th>
                        <th class="text-right">Subtotal</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var line in Model.ShoppingCart.ShoppingCartItems)
                    {
                        <tr>
                            <td class="text-center">@line.Amount</td>
                            <td class="text-left">@line.Watch.Name</td>
                            <td class="text-right">@line.Watch.Price.ToString("c")</td>
                            <td class="text-right">
                                @((line.Amount * line.Watch.Price).ToString("c"))
                            </td>
                            <td class="text-center">
                                <a asp-controller="ShoppingCart" asp-action="RemoveFromShoppingCart" asp-route-watchId="@line.Watch.WatchId">
                                    <i class="fas fa-trash"></i>
                                </a>
                            </td>
                        </tr>
                    }
                </tbody>
                <tfoot>
                    <tr>
                        <td colspan="3" class="text-right">Total:</td>
                        <td class="text-right">
                            @Model.ShoppingCartTotal.ToString("c")
                        </td>
                    </tr>
                </tfoot>
            </table>
            <div class="text-right">
                <a class="btn btn-success" asp-controller="Order" asp-action="Checkout">Check out</a>
            </div>
        </div>
    </div>
</section>